### ISSUE TITLE
Windows Font Preview Icon not ok

### ISSUE THREAD

**Issue by PaderDesign** [psb1558/Junicode-New#30] opened 2020-07-18 20:39 UTC
Hi Peter,
this is a minor issue, but I guess it is of interest to you:
In Windows we have this one page in the settings, where we can see all fonts installed.  The preview icon of JuniusX is not ok there. It shows three boxes instead of characters. I'm still on Windows 7 here, but could be the same under Windows 10. The attached screenshot illustrates the issue.
![Screenshot](https://user-images.githubusercontent.com/36140729/87861494-090e1400-c947-11ea-854b-62f436d16b85.png)
Friendly greetings

**Comment by psb1558** [comment] 2020-07-18 22:01
Thanks for the heads up. I've seen problems like this before: I'll look into it and find a fix.

**Comment by psb1558** [comment] 2020-07-19 01:11
I believe the codePageRamges and/or unicodeRanges fields of the OS/2 table have got to be set for the icon to display correctly on Windows systems. With that fix, anyway, it displays correctly on the Windows 7 machine in my basement. Updated source and static fonts are uploaded. @PaderDesign: Please leave a comment to let me know if the problem is fixed on your system.

**Comment by PaderDesign** [comment] 2020-07-28 23:54
Hello Peter, 
many thanks for locking into this and sorry for the late response. Already 10 days back, when you made the fix above, I tested the new version. And it is generally fixed. Take a look:
![Screenshot 2](https://user-images.githubusercontent.com/36140729/88739826-d2e94500-d13b-11ea-9efb-4bae9a6b3f0d.png)

You can see the old Junicode and the new Junius entry next to each other. Do you see the difference in the A's? Their bottom serifs look differently.
Well, one could think now, it is just a preview, but I wondered what might cause it. So, I compared the A's in four different graphic software tools. Turned out, that they render the serifs differently too. Some make an all straight bottom line, the others make is slightly hollow, and it depends on which font-weight I applied. The "JuniusX Condensed" works correct, as Junicode did. Well, I marked the wrong serifs in the image below with a red circle:
![Odd A-Serifes](https://user-images.githubusercontent.com/36140729/88740312-1a240580-d13d-11ea-8637-5ec6d28c156e.png)

Could it have other reasons, like graphics driver or outdated OS?

Friendly greetings

**Comment by psb1558** [comment] 2020-07-29 01:26
I think the problem is with the hinting of the font. What **should** happen (and I've hinted the A by hand to illustrate) is that the bottom of the serif should be straight at low resolutions and cupped at higher resolutions. Here it changes between 144 pixels per em (ppem) and 145:
<img width="323" alt="image" src="https://user-images.githubusercontent.com/16215767/88743755-7a9e4d00-d113-11ea-94b0-d56c20ee596d.png">
But I've noticed several problems. First, different applications may set up the graphics state differently, yielding different results, or they may use entirely different rendering systems. Magnify the serifs from Inkscape (left) and LibreOffice (right) and you can see a big difference: LibreOffice is using Windows ClearType (I'm not sure which of its several modes), while Inkscape is doing something different: maybe Windows grayscale or (since it's libre) maybe FreeType:
<img width="703" alt="image" src="https://user-images.githubusercontent.com/16215767/88744683-0dd88200-d116-11ea-929a-60d33e841cff.png">
PaintShop Pro and PhotoLine (I don't know these apps) are doing something different from both Inkscape and LO.

Another problem is that it looks as if the autohinting tool Ive been usind (ttfautohint) is misunderstanding the serifs of JuniusX entirely. I don't know whether it's the different version of ttfautohint or some change in the font (the serifs of JuniusX aren't substantially different from those in Junicode): I'll have to look into it and see if I can find a fix. I don't think I can hint this whole font by hand.

**Comment by psb1558** [comment] 2020-07-29 11:06
Looking into this issue further, it seems to me that ttfautohint is doing a pretty good job with the serifs of JuniusX. The only issue is that, when the cup of the serif is straightened, the bottom of the serif is positioned 1px below the baseline:
<img width="386" alt="image" src="https://user-images.githubusercontent.com/16215767/88792109-c202f880-d168-11ea-93d1-f8700dc4ca9e.png">
But as this is done consistently for all glyphs, it's not much of a problem. It straightens the bottoms of serifs at all resolutions up to 200 ppem, above which it switches hinting off altogether:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/16215767/88792558-66853a80-d169-11ea-81df-0b33def7dacc.png">
It may be possible to adjust cutoffs etc. to achieve better results at intermediate resolutions (e.g. 100-200 ppem): I'm reviewing the ttfautohint documentation to find out.

**Closed** 2020-10-03 04:09 UTC
