### ISSUE TITLE
Discretionary Ligatures (dlig) doc draft and issues

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-New#29] opened 2020-07-12 03:45 UTC
This is the first draft of the docs for Discretionary Ligatures `dlig` since much of it moved to `nalt`.
Most of it appears to work fine, with just a couple of issues.

The `longs c uniF23A` ligature does not appear to be working (for me).
It works fine in: FontCreator OpenType Designer
It works fine in: Crowbar (http://www.corvelsoftware.co.uk/crowbar/)
It works fine in: Affinity Publisher
Soooooo ... this may be another LibreOffice on Windows / Harfbuzz issue.
Does it work for you in LO on your Mac?

The other issue is the lowercase roman numerals appear to need some tightening.
So you may want to put that in your not-a-current-priority ToDo list.

[JuniusX_User_Guide_Discretionary_Ligatures_dlig_2020-07-11.pdf](https://github.com/psb1558/Junicode-New/files/4907964/JuniusX_User_Guide_Discretionary_Ligatures_dlig_2020-07-11.pdf)

![JuniusX_User_Guide_Discretionary_Ligatures_dlig_2020-07-11](https://user-images.githubusercontent.com/844920/87238236-e911aa00-c3b4-11ea-971d-62a224853382.png)

**Comment by psb1558** [comment] 2020-07-12 13:32
It looks good!

For the lc roman numbers I just accepted the default spacing and haven't yet done any fine-tuning. Will get to it.

I know what the problem is with longs c uniF23A, since I've been through it with PUA-encoded combining marks and got the explanation from the people on the Harfbuzz site. A PUA-encoded character has no characteristics at all: it belongs to no script, it's neither ltr nor rtl, etc. When applications break text into runs to feed to Harfbuzz (or another shaping engine), some assume that the PUA-encoded character has the same characteristics as the surrounding text, while others isolate it in its own run—and then, of course, it won't form ligatures. Neither approach is mistaken, but this is just one of several significant problems attending MUFI's practice of giving everything that's not in Unicode a code point in the PUA.

cv12 will give you that particular h--not uniF23A, but an unencoded duplicate of it (h.alt). I've just now added an unencoded duplicate of uniF4FA as longs_c_h.alt and altered the dlig rules:

```
    sub longs c uniF23A by longs_c_h.alt ;
    sub longs c h.alt by longs_c_h.alt ;
    sub longs.alt1 c uniF23A by longs_c_h.alt ;
    sub longs.alt1 c h.alt by longs_c_h.alt ;
```

Now you'll get the correct ligature if you use cv12 on the h instead of keying in F23A (but be sure to apply features to at least a whole word, <ss03><cv12>schon</cv12></ss03> not <ss03>s</ss03>c<cv12>h</cv12>on). You can search it on "sch," and screen-readers will get it right.

Would it be worth mentioning in your document that using an OpenType feature to get a character is always a better idea than keying in a PUA code?

**Comment by jsbien** [comment] 2020-07-12 13:44
On Sun, Jul 12 2020 at  6:33 -07, Peter Baker wrote:

[...]

> Would it be worth mentioning in your document that using an OpenType
> feature to get a character is always a better idea than keying in a
> PUA code?

I'm afraid it is not that simple because sometimes it is desirable to
use plain text encoding. Cf. section 12 of my paper mentioned earlier
(https://www.dropbox.com/sh/7em11ja17wzv9q0/AAAWD_eDLhgonFe_wvqQuLX1a?dl=0).

**Comment by kenmcd** [comment] 2020-07-14 03:16
> I know what the problem is with longs c uniF23A, since I've been through it with PUA-encoded combining marks and got the explanation from the people on the Harfbuzz site. A PUA-encoded character has no characteristics at all: it belongs to no script, it's neither ltr nor rtl, etc. When applications break text into runs to feed to Harfbuzz (or another shaping engine), some assume that the PUA-encoded character has the same characteristics as the surrounding text, while others isolate it in its own run—and then, of course, it won't form ligatures. Neither approach is mistaken, but this is just one of several significant problems attending MUFI's practice of giving everything that's not in Unicode a code point in the PUA.

Harfbuzz is not perfect - it has its own issues.
This is not the only issue I have found, or others have found.
This is why high-end graphics applications write their own text engines.
As I mentioned above, this works fine in Affinity Publisher.
I am sure it also works fine in Adobe InDesign.
Since this laptop is completely Adobe-free I have not tested.
If I had to I would test it in the InDesign I have in a VM (to keep Adobe hidden crap off this machine).

> Now you'll get the correct ligature if you use cv12 on the h instead of keying in F23A (but be sure to apply features to at least a whole word, schon not schon).

OK. I will try that when the fonts are updated.

> Would it be worth mentioning in your document that using an OpenType feature to get a character is always a better idea than keying in a PUA code?

Yes, that's a good idea. I will do that, with some info on why.
I should also include your _Guide to making searchable web pages with JuniusX_ as an appendix.
That way in the _why info_ I can point to it.

@jsbien
> I'm afraid it is not that simple because sometimes it is desirable to use plain text encoding. Cf. section 12 of my paper mentioned earlier

First, I am quite the newbie when it comes to medieval text, so I may miss the point.
I read your doc and assume you are referring to _12. Plain text encoding_.
I also read the Unicode FAQ and other docs.
One thing jumped out at me ... 
> Q: Can I define my own sequences?
A: No, that is the equivalent of trying to define an unassigned code point to be your own character. Private use characters should be used instead.

So, would all the variants need to be assigned Unicode code-points for this to be relevant to JuniusX?
Please explain in a way I could use in the docs for the more causual user (and me).
Thanks.

**Comment by jsbien** [comment] 2020-07-14 06:16
On Mon, Jul 13 2020 at 20:16 -07, kenmcd wrote:

[...]

> @jsbien
>
>>  I'm afraid it is not that simple because sometimes it is desirable to
>> use plain text encoding. Cf. section 12 of my paper mentioned earlier
>
> First, I am quite the newbie when it comes to medieval text, so I may
> miss the point.

And I'm quite ignorant of fonts. I have the over thousand pages book
"Fonts & Encodings" on my shelf but never manage to read it :-)

> I read your doc and assume you are referring to 12. Plain text
> encoding.

Yes.

> I also read the Unicode FAQ and other docs.
> One thing jumped out at me ...
>
>  Q: Can I define my own sequences?
>  A: No, that is the equivalent of trying to define an unassigned code
>  point to be your own character. Private use characters should be used
>  instead.

So in principle we should follow:

Q: How can I propose a standardized variation sequence?

A: You can initiate the process of requesting a variation sequence by
submitting an inquiry via the contact form.

I'm afraid it would take years to have the proposal accepted, if ever.

> So, would all the variants need to be assigned Unicode code-points for
> this to be relevant to JuniusX?

Yes and no. They may/should be assigned Private Use Area code-points,
which in a sense are Unicode code-points.

Other approach is to ignore the Unicode Consortium recomendations and
to reuse existing variation selectors for our purpose. Such "fait
accomplie" may perhaps facilitate the negotations with the Consortium
about the new selectors.

On the other hand it is not clear whether the Consortium is still to
be treated seriously, cf.
https://www.explainxkcd.com/wiki/index.php/1953:_The_History_of_Unicode

> Please explain in a way I could use in the docs for the more causual user (and me).

I will be only too happy to answer any additional questions.

**Comment by psb1558** [comment] 2020-07-14 10:02
I'm not sure I'm following all these points. I take Janusz's points (in the article linked to) about the difficulty of input, and also the problem of relying on metadata to identify variants (though the latter, at least, can be worked around: it's easy to imagine, say, designing a search that could find all words containing insular variants, and metadata would aid rather than hinder there).

I am chiefly concerned, though, with technical problems raised by PUA encoding, by searchability, and by accessibility. I was recently told (but haven't verified it for myself) that soon EU web accessibility rules will require that all text be readable by screen readers in pages posted by government-sponsored institutions (including universities). Since every PUA character is undefined as to content, script, and, well, everything, a text with PUA characters scattered through it presents obvious problems, especially when many of them are variants for familiar letters.

But when we're talking about input we're talking about production, and when we're talking about accessibility we're talking about final product, and it's not at all difficult to envision a process that gets you from the convenience of having a code point in the beginning to accessibility at the end.

**Comment by jsbien** [comment] 2020-07-14 10:11
What about having the best of both worlds and assigning every variant to a PUA character? Would be the price of it prohibitively high?

**Comment by psb1558** [comment] 2020-07-14 13:33
The price of PUA encoding is broken behavior in certain contexts, especially (but not exclusively) PDFs. To demonstrate, I've generated a little document, PUA-demo.pdf, which I've dropped into the docs directory along with its LibreOffice source. You can experience the problems for yourself by searching for various words and letter-sequences.

The JuniusX workaround for this problem is to echo certain PUA-encoded characters as unencoded glyphs (this make the font only a few bytes bigger). Where I've done this, you get the unencoded version when you use an OpenType feature, with the result that your text can be searched and is handled correctly by screen readers. Use an OpenType feature to generate a character with a PUA encoding and it will work properly in some application but not in others. Enter a PUA-encoded character directly and it will be broken everywhere.

Best practice in font production is now thought to be to avoid use of the PUA for any character (or composite) that can be mapped to Unicode values, but instead to use unencoded variants. Thus the PUA is useful for dingbats, logos and the like but not for variants of "a" or letter + diacritic combinations.

**Comment by jsbien** [comment] 2020-07-14 15:55
On Sun, Jul 12 2020 at  6:33 -07, Peter Baker wrote:

[...]

> Would it be worth mentioning in your document that using an OpenType
> feature to get a character is always a better idea than keying in a
> PUA code?

Would you agree to replace the word 'always' by 'mostly', 'usually' or
something similar?

**Comment by psb1558** [comment] 2020-07-14 16:16
Okay by me. Or it could say that use of OpenType features should generally be preferred to the direct input of PUA-encoded characters when the character is a variant of a Unicode-encoded character—for example, the uncial **a** (prefer **a** with cv01 to U+F214). But MUFI has many characters with no Unicode equivalent (for example, the groschen sign (U+F2E9)), and for these, the use of PUA code points is not to be avoided.

**Closed** 2021-04-29 11:56 UTC
