### ISSUE TITLE
JuniusX vs Junicode

### ISSUE THREAD

**Issue by zenny** [psb1558/Junicode-New#53] opened 2021-04-30 09:30 UTC
Hi,

Thanks for reworking on Junicode. I am redirected from https://github.com/google/fonts/issues/2080

Meanwhile, I noticed that JuniusX is not as clear as Junicode. I am a happy with Junicode except a few glyphs like ö, ä not working while italicized in Junicode. The closest to Junicode is JuniusX Medium, yet eye straining and some letters looks less beautiful than in Junicode (for example, g and &)

As for me, Junicode is the best looking font for legibility if some glyph issues are sorted out. Opinions may differ, but a picture speaks 1000 words:

![pic-selected-210430-1115-55](https://user-images.githubusercontent.com/1653166/116676137-e8c7b700-a9a6-11eb-8b37-c2c770029715.png)

Cheers, and stay safe,
/z

**Comment by sakkamade** [comment] 2021-04-30 10:03
If you are talking of *italic line*, you should read the main page of repository:
> All this is very much in progress. As of 5 December 2020, the roman face is complete (though metrics, anchors, and some features still need work), __and work on the italic is about 66% complete.__

The italic is not yet present.
Also, read https://github.com/psb1558/Junicode-New/discussions/52#discussioncomment-606055

If about the width―try Regular version.

**Comment by psb1558** [comment] 2021-04-30 12:05
Hi @zenny, and thanks for your comments!

The faulty advance width of the **fö** ligature in Junicode Italic is a bug, and I'll try to get that fixed. I don't see a problem with **ä** (where the left sidebearing and advance width are identical to **a**), but if you come across problems with other glyphs in Junicode, please do mention them.

As @sakkamade mentioned, there is no JuniusX Italic yet. Word processing software, and also (I believe) browsers, will simply skew the Regular face, as in your sample.

JuniusX Regular has outlines nearly identical to Junicode Regular, while JuniusX Medium is a bit darker:
<img width="486" alt="image" src="https://user-images.githubusercontent.com/16215767/116691376-bad37a00-a988-11eb-8508-6ba4ac7d1a97.png">
In the Regular faces, some outlines are slightly different in JuniusX:
<img width="246" alt="image" src="https://user-images.githubusercontent.com/16215767/116691899-80b6a800-a989-11eb-955c-f8eee1030744.png">
(where Junicode Regular is the red outline). My hope is that the revised outlines are better than the old ones, but as this project is extremely beta, I am very open to specific suggestions for improvement.

**Comment by sakkamade** [comment] 2021-04-30 20:42
@zenny "g" indeed looks weird at your picture.

> I tried regular version, but the space between characters are too large.

Hm, curious. I wager the question is your environment or the version of typeface which you are using.

I cannot reproduce it even without kerning and even with size of 16px:

![juni-typeface](https://user-images.githubusercontent.com/62730422/116751343-69140980-a9f3-11eb-9a9a-5e3a71d751d1.png)

**Comment by kenmcd** [comment] 2021-04-30 22:15
> Meanwhile, I noticed that JuniusX is not as clear as Junicode. I am a happy with Junicode except a few glyphs like ö, ä not working while italicized in Junicode. The closest to Junicode is JuniusX Medium, yet eye straining and some letters looks less beautiful than in Junicode (for example, g and &)

This looks like the crappy screen text rendering in LibreOffice on lower resolution screens.
You can tell by the odd gaps between letters (such as the "ed" in Medium in the first image).

Here is the same text on a high resolution display:  

![Junicode vs JuniusX on LO](https://user-images.githubusercontent.com/844920/116758547-22a7b600-a9c5-11eb-9a5a-ee8be090d32b.png)  

On your display to see how it will actually print you need to zoom-in by at least 300%, or more.
That is the only way to get enough pixels to work around the LO display limitations (bugs).
Or _Export to PDF_ to see the fonts as they actually look.

**Comment by psb1558** [comment] 2021-04-30 22:58
@sakkamade: Amazing how bad JuniusX looks in your samples! Can you tell me some details about your display? What system you're running and what software is displaying the font? I'm afraid that ttfautohint isn't working well enough for this font.

The Junius family of fonts always looks small because the x-height is small, as in a number of old-style fonts. I use a 12pt type to look approximately like 10pt.

**Comment by sakkamade** [comment] 2021-04-30 23:54
@psb1558 Hahaha, why thank you. 
This is from GIMP, I have used it precisely to point out that "g" looks nice under any circumstances :heart:. 
But indeed, appearance is not the best.

**Comment by zenny** [comment] 2021-05-01 07:52
> Hi @zenny, and thanks for your comments!
> 
> The faulty advance width of the **fö** ligature in Junicode Italic is a bug, and I'll try to get that fixed. 

Thanks for your prompt response. Junicode is the most preferred font in my case. Thanks for creating such a gem!

>I don't see a problem with **ä** (where the left sidebearing and advance width are identical to **a**), but if you come across problems with other glyphs in Junicode, please do mention them.

I shall.
> 
> As @sakkamade mentioned, there is no JuniusX Italic yet. Word processing software, and also (I believe) browsers, will simply skew the Regular face, as in your sample.
> 
> JuniusX Regular has outlines nearly identical to Junicode Regular, while JuniusX Medium is a bit darker:
> <img alt="image" width="486" src="https://user-images.githubusercontent.com/16215767/116691376-bad37a00-a988-11eb-8508-6ba4ac7d1a97.png">
> In the Regular faces, some outlines are slightly different in JuniusX:
> <img alt="image" width="246" src="https://user-images.githubusercontent.com/16215767/116691899-80b6a800-a989-11eb-955c-f8eee1030744.png">
> (where Junicode Regular is the red outline). My hope is that the revised outlines are better than the old ones, but as this project is extremely beta, I am very open to specific suggestions for improvement.

**Comment by psb1558** [comment] 2021-05-01 12:20
It's pretty clear that on systems like Windows that us a font's hinting, both Junicode and JuniusX look worse with hinting than without at low resolution. I've done a couple of things to address the problem. One is to change the gasp table, which recommends sizes at which hinting occurs. This won't do any good if an application doesn't read the gasp table (not all do), but it may help sometimes.

The other is to supply an OTF version of JuniusX, which may render better than the TTF version on some displays. Find it in the /fonts/otf folder of the respository. Don't install it alongside the TTF version: use one or the other.

The best possible solution would be to manually hint the font (and I'm working on a limited set of manual hints for the variable font). But with 25 font files, each containing more than 1,600 outlines, it's more than one person can do.

**Comment by zenny** [comment] 2021-05-01 16:48
> It's pretty clear that on systems like Windows that us a font's hinting, both Junicode and JuniusX look worse with hinting than without at low resolution. I've done a couple of things to address the problem. One is to change the gasp table, which recommends sizes at which hinting occurs. This won't do any good if an application doesn't read the gasp table (not all do), but it may help sometimes.
> 
> The other is to supply an OTF version of JuniusX, which may render better than the TTF version on some displays. Find it in the /fonts/otf folder of the respository. Don't install it alongside the TTF version: use one or the other.
> 
> The best possible solution would be to manually hint the font (and I'm working on a limited set of manual hints for the variable font). But with 25 font files, each containing more than 1,600 outlines, it's more than one person can do.

@psb1558 Thanks from the bottom of the heart for your effort to create "Junicode" in particular, thought there are some bugs to with some glyphs like ö when italisized. Looking forward to the debugged version.

Meanwhile, let me inform yout that Junicode (not JuniusX) in Abiword (in Linux) renders as a compressed black box as appears below. 

![pic-selected-210501-1820-52](https://user-images.githubusercontent.com/1653166/116789147-adfc7680-aaad-11eb-96ec-0830bfd95b97.png)

Cheers,

**Comment by psb1558** [comment] 2021-05-01 18:52
Ouch! I'll fire up the Linux box and have a look.

**Comment by psb1558** [comment] 2021-05-01 19:21
Here's another scheme, which seems to work better: Use the Glyphs semi-manual TrueType editor to hint one of the masters: Glyphs then propagates the hints to all the generated fonts. On a first go, the results are like this:
<img width="693" alt="image" src="https://user-images.githubusercontent.com/16215767/116792572-84345700-aa8f-11eb-848a-f30727b37e9f.png">
(Screenshot from LIbreOffice, running on the most horribly primitive Windows 10 (ClearType) machine I could get my hands on.) There are still some problems, e.g. with **t**, **E**, **G**, but these shouldn't be hard to fix. The fonts I've just posted have hints only for A-Z a-z and basic punctuation, but hinting goes incredibly fast in this editor. As a bonus, the font files are significantly smaller than when hinted with ttfautohint.

**Comment by zenny** [comment] 2021-05-02 20:37
> Hi @zenny, and thanks for your comments!
> 
> The faulty advance width of the **fö** ligature in Junicode Italic is a bug, and I'll try to get that fixed. 

@psb1558, I appreciate if you update here after fixing the Junicode italics glyph bug. Appreciate that. Thanks again for the unbelievably beautiful font, Junicode!

Cheers, and stay safe,
/z

**Comment by sakkamade** [comment] 2021-05-02 22:00
> after fixing the Junicode italics

I wonder if that will ever be fixed in original Junicode.  
All the labour at the moment seemingly proceeds over the JuniusX, you may expect only JuniusX Italic.

Am I wrong, @psb1558 ?

**Comment by psb1558** [comment] 2021-05-02 22:46
I'm going to try to fix it. Trouble is, my workflow for Junicode was Fontforge + aging Adobe tools, and now it's Glyphs + fontmake, so I have to see if that older setup is still functional (or can be revived). But I'd like to do it, because I know of one other bug that needs fixing, and it's been gnawing at me.

**Comment by psb1558** [comment] 2021-05-03 12:27
It occurred to me that a simple fix like this one could be accomplished with ttx, so that's what I have done. (The fixed Junicode-Italic.ttf is now in the [legacy](https://github.com/psb1558/Junicode-New/tree/master/legacy) folder.) And since I intend only to make simple fixes of this kind, I've posted the ttx file as the new source for Junicode-Italic.

**Comment by psb1558** [comment] 2021-05-04 10:27
As teh substantive part of this thread was fixing the fö ligature, this can be closed now, I think.

**Closed by psb1558** 2021-05-04 10:27 UTC

**Comment by zenny** [comment] 2021-05-05 07:53
> As teh substantive part of this thread was fixing the fö ligature, this can be closed now, I think.

@psb1558 So nice of you to fix the bug despite your migration to new environment. Hats off to you! :+1:

**Comment by zenny** [comment] 2021-12-01 11:37
@psb1558 What a nice font that I could not live without (junicode, not juniusX).

The reason why I am still with Junicode (way better in look as of below):

1. JuniuX bold fontface does not rendered into PDF by libreoffice (libreoffice-7.1.3.2). The original in libreoffice looks like:

![pic-selected-211201-0900-55](https://user-images.githubusercontent.com/1653166/144227365-dee642f2-3f76-4ca4-865b-b88b47799314.png)

And when exported to the PDF, the Bold face of Junius X fails to render. See below in pdf:

![pic-selected-211201-0902-13](https://user-images.githubusercontent.com/1653166/144227443-917e5636-5f94-4ddf-a15b-16dc81f49a20.png)

2. Above all I have put forth the reasons in above screenshots in (1) why I still prefer Junicode over JuniusX with some evidence of the overlaps, disappearance and uneven spacing.

Cheers,
/z

**Comment by psb1558** [comment] 2021-12-01 12:16
_Of course_ you prefer old Junicode to new Junicode. I do too, and that's why I encourage people to go on using Junicode 1 (legacy Junicode) for the time being instead of Junicode 2 (formerly JuniusX).

That's because Junicode 2 is in development. It is a beta. It's like a house under construction. You might well say, "I like the old house better than the new house. Look! The old one has such a nice roof, and the new one doesn't even have a roof. And the plumbing doesn't work right in the new house, though it was fine in the old house." All true, but you're criticizing a house under construction for being under construction.

Font development is slow and difficult. Forget Junicode 2 for now, but make a note to check back in a year or two—whenever I manage to finish it. I promise, you'll like it.

**Comment by zenny** [comment] 2021-12-01 18:12
> _Of course_ you prefer old Junicode to new Junicode. I do too, and that's why I encourage people to go on using Junicode 1 (legacy Junicode) for the time being instead of Junicode 2 (formerly JuniusX).
> 
> That's because Junicode 2 is in development. It is a beta. It's like a house under construction. You might well say, "I like the old house better than the new house. Look! The old one has such a nice roof, and the new one doesn't even have a roof. And the plumbing doesn't work right in the new house, though it was fine in the old house." All true, but you're criticizing a house under construction for being under construction.
> 
> Font development is slow and difficult. Forget Junicode 2 for now, but make a note to check back in a year or two—whenever I manage to finish it. I promise, you'll like it.

Oh I did not meant to take it on programming side which is irreparable, just pointed to aesthetic side. My comments are not about existentialism, but about inheriting the best part of Junicode to JuniusX. Anyway, thanks for Junicode. Cheers,
