### ISSUE TITLE
A variant of a with ogonek/stroke

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-New#14] opened 2020-05-30 12:55 UTC
Before a with ogonek became generally used for a nasal sound in Polish, a with stroke was used instead.  In a diachronic [IMPACT corpus](https://ispan.waw.pl/journals/index.php/cs-ec/article/view/cs.2014.008) a with stroke has about [30000 occurences](http://bc.klf.uw.edu.pl/289/) (while a with ogonek has about 40000). In the corpus the character was represented respectively by LATIN SMALL/CAPITAL LETTER A WITH STROKE (U+2C65 and U+023A), so it can be considered a glyph variant of this codepoint; however using U+2C65 and U+023A is not a generally accepted standard, so treating it as a variant of a with ogonek also has an advantage.
Reportedly the stroke had different shapes, but supporting only one variant illustrated below is in my opinion completely sufficient.
![awithstroke-twice](https://user-images.githubusercontent.com/8024702/83328720-6e1d8580-a285-11ea-9a13-8f8482732875.png)
![ZasadyOCR_15_a](https://user-images.githubusercontent.com/8024702/83328722-6eb61c00-a285-11ea-9f60-3f64121da991.png)

**Comment by psb1558** [comment] 2020-05-30 13:00
Do you have any images of the capital? (And, btw, should there be capital versions of the ø variants?)

**Comment by jsbien** [comment] 2020-05-30 13:12
The first hit in the IMPACT corpus:
![NT2186Astroke](https://user-images.githubusercontent.com/8024702/83329124-e84f0980-a287-11ea-91b3-cf1383a84a76.png)
I will look for more examples.

**Comment by psb1558** [comment] 2020-05-30 13:19
I really like that! Would be interested in any other variants.

**Comment by jsbien** [comment] 2020-05-30 13:25
Another volume of the same work:
![NT466Astroke](https://user-images.githubusercontent.com/8024702/83329355-51834c80-a289-11ea-8c4b-c8ea775c1fda.png)
Another book:
![Oekonomika26Astroke](https://user-images.githubusercontent.com/8024702/83329375-6069ff00-a289-11ea-961c-1787cd53fb2e.png)
And a strange ogonek-stroke I noticed now for the first time:
![Rymy307Astroke](https://user-images.githubusercontent.com/8024702/83329401-868f9f00-a289-11ea-9c2b-317941ab3c8b.png)

**Comment by jsbien** [comment] 2020-05-30 13:33
As for the capital versions of the ø variant, there is no real need for it, but they may be added just for completenes.

**Comment by psb1558** [comment] 2020-06-01 01:52
Do the variants of lowercase ą with the line through and the line above and below ever occur in roman style, or just italic?

I don't believe in case pairing for its own sake; if uppercase variants of ø would get no use, I won't add them.

**Comment by jsbien** [comment] 2020-06-01 06:46
Unfortunately the IMPACT corpus is now not fully functional and I cannot find easily specific examples. Definitely the character is used not only in italic style, but the other style in that time was often a kind of fraktur, which is now rendered just as a roman style. So, with this qualification, I think the answer is yes.

**Comment by psb1558** [comment] 2020-06-01 09:14
Thanks—I'll run some images by you later today and get your advice.

**Comment by psb1558** [comment] 2020-06-01 10:49
A first attempt at lowercase roman.
<img width="286" alt="image" src="https://user-images.githubusercontent.com/16215767/83402006-f9a52c80-a3d3-11ea-9aa0-48952d6136be.png">
Suggestions?

**Comment by psb1558** [comment] 2020-06-01 10:51
I feel more confident about the uppercase, since the models are very clear.
<img width="312" alt="image" src="https://user-images.githubusercontent.com/16215767/83402196-47219980-a3d4-11ea-8745-6b27ab3f6f10.png">

**Comment by jsbien** [comment] 2020-06-01 11:02
Uppercase is OK. As for lower case, I think the crossbar should moved a little to right and upwards, the lines should cross, not just touch.  I uoload another example, but I haven't found yet a really good model.
![00433088k1skapcy](https://user-images.githubusercontent.com/8024702/83402946-06437800-a408-11ea-9b1a-6683fc442ed2.png)

**Comment by psb1558** [comment] 2020-06-01 11:22
This is a big help, but other examples would be welcome.

**Comment by psb1558** [comment] 2020-06-01 11:33
Like this?
<img width="64" alt="image" src="https://user-images.githubusercontent.com/16215767/83405021-ac2bbe00-a3d9-11ea-90b0-1020781f8bf7.png">
It's tempting to widen the lower-right curve just a little bit to accommodate the diagonal stroke (though I don't think whoever cut the original type did so):
<img width="68" alt="image" src="https://user-images.githubusercontent.com/16215767/83405169-f01ec300-a3d9-11ea-88da-361a82c46d45.png">

**Comment by jsbien** [comment] 2020-06-01 11:41
I think the stroke can be shorter and not so steep. I will look for a good model, but I want to make haste slowly and try first to circumvent some technical problems with our corpus,

**Comment by jsbien** [comment] 2020-06-01 11:47
![00436549skuteczna](https://user-images.githubusercontent.com/8024702/83406174-6210ff80-a40e-11ea-92cc-7214c6a95735.png)
This looks quite good, but it seems to me that the stroke is more to the left than usual.

**Comment by psb1558** [comment] 2020-06-01 12:24
I think it's pretty clear that these old punch cutters were working with existing matrices for a, and we're seeing various responses to the fact that the lower-right curve of a is not wide enough for a crossing stroke. The stroke in the "skąpey" example is quite steep, about 20°, which is one way of dealing with the problem, but even so ink spread has made it quite indistinct. In the "skuteczną" example the stroke is a more comfortable 40°, but there's no way to make that cross only the curve. I can widen the curve a bit and make the angle 20°, so
<img width="68" alt="image" src="https://user-images.githubusercontent.com/16215767/83407679-3fb3bd80-a3df-11ea-9166-545dae64b3c0.png">
If I make the angle 30° I need to nudge the stroke just a little bit left:
<img width="62" alt="image" src="https://user-images.githubusercontent.com/16215767/83407885-a20cbe00-a3df-11ea-9fe9-5e6aa6ba75d3.png">
At 40° it starts to look awkward (to my eye, anyway)
<img width="62" alt="image" src="https://user-images.githubusercontent.com/16215767/83408092-092a7280-a3e0-11ea-887b-87d46e49b30a.png">
unless you take the approach of the ą in the  "skuteczną" example:
<img width="57" alt="image" src="https://user-images.githubusercontent.com/16215767/83408484-adacb480-a3e0-11ea-846f-d40acf75f281.png">
I think the 30° stroke with the widened curve on the a looks best (the 2nd image), but I'm not thinking about it historically.

**Comment by jsbien** [comment] 2020-06-01 13:14
![00436642 miesiaca](https://user-images.githubusercontent.com/8024702/83412093-dbfab600-a419-11ea-8206-9343668ebed6.png)
![00436637laska](https://user-images.githubusercontent.com/8024702/83412157-f339a380-a419-11ea-8147-cbadfd864878.png)
![00436610szukaja](https://user-images.githubusercontent.com/8024702/83412226-05b3dd00-a41a-11ea-8907-703472c2a0b9.png)
![00436554wziawszy](https://user-images.githubusercontent.com/8024702/83412264-1a907080-a41a-11ea-8941-8ba49b90a0cb.png)
From an aestetic point of view the version from the first scan above seems quite nice, but your proposal is also OK.

**Comment by psb1558** [comment] 2020-06-01 13:56
I like that. Position, angle, wedge-shaped stroke. I'll work on this later today.

**Comment by jsbien** [comment] 2020-06-01 14:52
FYI, it comes from https://cbdu.ijp.pan.pl/2910/.

**Comment by psb1558** [comment] 2020-06-01 16:03
The **a** is very different in this font, and I have to stick with the one in Junicode, but I can reproduce the position, shape and size of the cross-stroke:
<img width="57" alt="image" src="https://user-images.githubusercontent.com/16215767/83428142-e1e39d80-a3ff-11ea-823a-79e0a460208a.png">

**Comment by psb1558** [comment] 2020-06-01 16:06
> FYI, it comes from https://cbdu.ijp.pan.pl/2910/.

It's a beautiful piece of printing.

**Comment by jsbien** [comment] 2020-06-01 16:27
The shape is very nice.

**Comment by psb1558** [comment] 2020-06-01 16:39
The four masters of this font:
<img width="280" alt="image" src="https://user-images.githubusercontent.com/16215767/83431190-f37b7400-a404-11ea-9787-6ed222156ef1.png">

**Comment by psb1558** [comment] 2020-06-01 16:43
This same work has a very nice eogonek, which I think as I'll use as a model for the shape and position of the stroke in that other issue:
<img width="407" alt="image" src="https://user-images.githubusercontent.com/16215767/83431491-6f75bc00-a405-11ea-8d37-c96f5fcea2c9.png">

**Comment by jsbien** [comment] 2020-06-01 17:03
OK. BTW, this is an ephemeral print, I wander whether anybody knows which printing house it comes from. An interesting topic of research :-)

**Comment by psb1558** [comment] 2020-06-02 00:33
Second alternate:
<img width="399" alt="image" src="https://user-images.githubusercontent.com/16215767/83467146-13cc2280-a447-11ea-9853-b45c063458d7.png">

**Comment by jsbien** [comment] 2020-06-02 04:42
OK

**Comment by psb1558** [comment] 2020-06-03 00:30
Can you find any more images of the italic aogoneks? It's very har to make out what's going on in the one on the right:
![image](https://user-images.githubusercontent.com/16215767/83582586-e8613a80-a50f-11ea-8236-c23a11dfccf4.png)
Which ot the three is most common?

**Comment by jsbien** [comment] 2020-06-03 06:09
![00436695nasladowca](https://user-images.githubusercontent.com/8024702/83600735-82a49b00-a56f-11ea-8f79-ef556c48d0c8.png)
![00436726tysiac](https://user-images.githubusercontent.com/8024702/83600779-9e0fa600-a56f-11ea-9a43-0c0a7fa298dd.png)
![00436806mila](https://user-images.githubusercontent.com/8024702/83600814-af58b280-a56f-11ea-8999-420b4f976f94.png)
![00436871cera](https://user-images.githubusercontent.com/8024702/83600838-bbdd0b00-a56f-11ea-8562-6122fa0625eb.png)
These are all the examples I can provide now. Yesterday I made a systematic search in our corpus and other examples I can find only incidentally.
 In your post the first letter on the left is a standard Unicode a with stroke. It would be nice to have the variant for the one in the middle, but it can be either approximated by the left one or perhaps rendered with a combining stroke. The one on the right is the most important, it seems also most common.

**Comment by psb1558** [comment] 2020-06-03 10:39
I think I can more or less see what's going on. I've added U+023A and U+2C65 to the roman font, but I've echoed U+2C65 as aogonek.alt2 and added it to cv02. (cv02 should be used to produce this shape, since it then remains searchable as aogonek U+0105.)
<img width="51" alt="image" src="https://user-images.githubusercontent.com/16215767/83627344-c3e37d80-a564-11ea-8b22-fb9b7ff8c0a7.png">

Is a shape matching U+023A ever used for Aogonek?
<img width="85" alt="image" src="https://user-images.githubusercontent.com/16215767/83627286-ac0bf980-a564-11ea-8b13-252e0acd98ad.png">

**Comment by jsbien** [comment] 2020-06-03 10:57
Nasals in Polish never start a word, but upper case versions may appear e.g. in capitalized titles. So the answer is yes.

**Comment by psb1558** [comment] 2020-06-03 19:19
Italic.
<img width="285" alt="image" src="https://user-images.githubusercontent.com/16215767/83679580-9e2e9680-a5ad-11ea-83b6-970c1e679db3.png">

**Comment by psb1558** [comment] 2020-06-03 21:09
Italic caps.
<img width="328" alt="image" src="https://user-images.githubusercontent.com/16215767/83689411-fe790480-a5bc-11ea-9598-b0c20ca7ac7e.png">

**Comment by jsbien** [comment] 2020-06-04 04:49
OK except the lower case on the right. I don't think the stroke should be broken.
BTW, a general remark. Contrary e.g. to Adam Twardoch (https://junicode.sourceforge.io/ecaudata.html) I don't believe in one canonical shape and position of ogonek. There are so many variants of it in the texts that the choice which shape use in a font always will be more or less arbitrary.

**Comment by psb1558** [comment] 2020-06-04 09:49
Thanks--I'll work on the last lowercase shape.

Interestingly, Adam Twardoch contacted me years ago about the position of the ogonek in eogonek and talked me into moving it. But I also kept the older shape, and that's why there has been an alternate eogonek in Junicode for so long.

**Comment by psb1558** [comment] 2020-06-05 10:37
A simpler approach.
<img width="75" alt="image" src="https://user-images.githubusercontent.com/16215767/83867204-105ec280-a6f7-11ea-8315-60a03cd89959.png">

**Comment by jsbien** [comment] 2020-06-05 10:50
Sorry, but I think we don't need a glyph like that. In all a with stroke I know the a is crossed by a single continuos stroke. Your glyph is similar to "o with horns" from issue #3, but we don't need "a with horns".

**Comment by psb1558** [comment] 2020-06-05 10:53
I thought it was like the second of your three italic examples in your first post. I suppose I misinterpreted it, and will delete this.

**Comment by jsbien** [comment] 2020-06-06 04:49
The print quality of some texts in the corpus is horribly and identifying a character can be quite a challenge.

**Closed** 2020-06-30 13:06 UTC
